#
# Copyright (C) 2022 Jianhui Zhao <zhaojh329@gmail.com>
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=WAN
APP_NAME:=wan
APP_DEPENDS:=+lua-eco-uci +lua-eco-ubus +lua-eco-file

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
