#
# Copyright (C) 2025
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=Wireless Repeater
APP_NAME:=wireless-repeater

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
